apiVersion: fn.kpt.dev/v1alpha1
kind: UpdateKSopsSecrets
metadata:
  name: test-update-ksops-secrets
secret:
  type: Opaque
  references:
  - unencrypted-secrets
  - unencrypted-secrets-config-txt
  - test-update-ksops-secrets
  items:
  - test
  - test2
  - UPPER_CASE
  - config.txt
  - same-secret-and-secret-ref-name
recipients:
- type: age
  recipient: age1x7pzjx4r05ar95pulf20knx0mkscaxa0zhtqr948wza3863fvees8tzaaa
- type: pgp
  recipient: F532DA10E563EE84440977A19D0470BDA6CDC457
- type: pgp
  recipient: 380024A2AC1D3EBC9402BEE66E38309B4DA30118
  publicKeySecretReference:
    name: gpg-publickeys
    key: 380024A2AC1D3EBC9402BEE66E38309B4DA30118.gpg
