apiVersion: fn.kpt.dev/v1alpha1
kind: UpdateKSopsSecrets
metadata:
  name: test-update-ksops-secrets
secret:
  type: Opaque
  references:
  - unencrypted-secrets
  - unencrypted-secrets-config-txt
  items:
  - test
  - test2
  - UPPER_CASE
  - config.txt
recipients:
- type: age
  recipient: age1x7pzjx4r05ar95pulf20knx0mkscaxa0zhtqr948wza3863fvees8tzaaa
