#!/bin/sh

set -e

mkdir -p ./generated

run() {
  name="$1"
  expected="$2"

  echo "+------"
  echo "| Test $name ..."
  echo "+------"

  echo "+ Kpt function execute:"
  kpt fn eval \
    --exec /usr/local/bin/kpt-update-ksops-secrets \
    --fn-config ./update-ksops-secrets.yaml \
    --truncate-output=false

  echo "+ Generated source package tree:"
  kpt pkg tree

  echo "+ Describe files contents:"
  find . -type f > /tmp/.files
  while read -r file; do
    printf "# %s\n" "$file"
    cat "$file"
    echo "---"
  done < /tmp/.files

  echo "+ Kustomize manifests build:"
  kustomize build --enable-alpha-plugins . | tee /tmp/.kustomize-build.output


  check=$(diff /tmp/.kustomize-build.output "$expected")
  if [ -z "$check" ]; then
    echo "+ Build OK"
  else
    echo "+ Build Failed"
    exit 1
  fi
}

##
# Main
##

# Expected result
cat <<EOF > /tmp/.kustomize-build.expected
apiVersion: v1
data:
  UPPER_CASE: dXBwZXJfY2FzZQ==
  config.txt: Y29uZmlnLnR4dAo=
  same-secret-and-secret-ref-name: dGVzdA==
  test: dGVzdA==
  test2: dGVzdDI=
kind: Secret
metadata:
  annotations:
    kustomize.config.k8s.io/behavior: merge
  name: test-update-ksops-secrets
type: Opaque
EOF

# Passing
# + Function Config
#   + update-ksops-secrets.yaml
# + Unencrypted secrets
#   + unencrypted-secrets.yaml
#   + unencrypted-secrets-config-txt.yaml
run "full generation" "/tmp/.kustomize-build.expected"

# Drop unencrypted secret to simulate partial update
rm -f unencrypted-secrets-config-txt.yaml
run "partial generation" "/tmp/.kustomize-build.expected"

# Drop all remaining unencrypted secret
rm -f unencrypted-secrets.yaml
rm -f test-update-ksops-secrets.yaml
run "no updated generation" "/tmp/.kustomize-build.expected"

# Cleanup unused generated file
# Expected result
cat <<EOF > /tmp/.kustomize-build-cleanup-unused-generated-file.expected
apiVersion: v1
data:
  UPPER_CASE: dXBwZXJfY2FzZQ==
  config.txt: Y29uZmlnLnR4dAo=
  same-secret-and-secret-ref-name: dGVzdA==
kind: Secret
metadata:
  annotations:
    kustomize.config.k8s.io/behavior: merge
  name: test-update-ksops-secrets
type: Opaque
EOF

sed -i '/- test$/d' update-ksops-secrets.yaml
sed -i '/- test2$/d' update-ksops-secrets.yaml
run "cleanup unused generated file" "/tmp/.kustomize-build-cleanup-unused-generated-file.expected"
