name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  ci:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set variables output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.6.14

      - name: run integration test
        run: earthly --ci --verbose --allow-privileged +integration-image-test

      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and publish image
        run: earthly --ci --verbose --push +image --IMAGE_TAG=${{ steps.vars.outputs.tag }}
